[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib @ ^6.0.0
    mikalhart/TinyGPSPlus @ ^1.0.3
    h2zero/NimBLE-Arduino @ ^1.4.1

build_flags = 
    -D LORA_FREQ=865.0
